/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package echo.server;

import java.net.ServerSocket;

public class App {
    public String getGreeting() {
        return "Welcome to the Echo Server!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ServerSocket serverSocket = EchoServer.startServer();
    }
}
