/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package echo.server;

import java.net.ServerSocket;

import static echo.server.EchoServer.startServer;

public class App {

  public static void main(String[] args) {
    Console.print("Welcome to the Echo Server!");
    Console.print("Starting Server...");
    ServerSocket serverSocket = startServer(0);
    Console.print("Server Started!");
  }
}
